version: '3.7'
services:
  db:
    image: mongo
    container_name: "mongo_db"
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_db:/data/db

  bot:
    container_name: "bot_rtl"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    depends_on:
      - db

volumes:
  mongo_db:
